language: objective-c
osx_image: xcode9
branches:
  only:
    - master
env:
  global:
  - PROJECT=Rapid.xcodeproj
  - IOS_FRAMEWORK_SCHEME="Rapid iOS"
  - MACOS_FRAMEWORK_SCHEME="Rapid macOS"
  - TVOS_FRAMEWORK_SCHEME="Rapid tvOS"
  matrix:
    - DESTINATION="OS=11.0,name=iPhone 8"           SCHEME="$IOS_FRAMEWORK_SCHEME"      RUN_TESTS="YES"   POD_LINT="YES"
    - DESTINATION="OS=10.3.1,name=iPhone 7"           SCHEME="$IOS_FRAMEWORK_SCHEME"      RUN_TESTS="NO"   POD_LINT="NO"
    - DESTINATION="OS=9.0,name=iPhone 6"           SCHEME="$IOS_FRAMEWORK_SCHEME"      RUN_TESTS="NO"    POD_LINT="NO"
    - DESTINATION="OS=8.1,name=iPhone 4S"          SCHEME="$IOS_FRAMEWORK_SCHEME"      RUN_TESTS="NO"    POD_LINT="NO"

    - DESTINATION="OS=11.0,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"     RUN_TESTS="YES"   POD_LINT="NO"
    - DESTINATION="OS=10.2,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"     RUN_TESTS="NO"   POD_LINT="NO"
    - DESTINATION="OS=9.0,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"     RUN_TESTS="NO"    POD_LINT="NO"

    - DESTINATION="arch=x86_64"                       SCHEME="$MACOS_FRAMEWORK_SCHEME"    RUN_TESTS="YES"   POD_LINT="NO"
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi