source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'10.0'
project 'ExamplePodApp.xcodeproj'

# ignore all warnings from all pods
inhibit_all_warnings!
use_frameworks!

def shared_pods

pod 'Rapid'

end



target 'ExamplePodApp' do
    shared_pods
end
